spring.application.name=StocksMCP
server.port=9191

alpha-vantage.api-key=${ALPHA_VANTAGE_API_KEY}
alpha-vantage.base-url=https://www.alphavantage.co/query

spring.main.banner-mode=off
logging.pattern.console=
logging.level.root=OFF



